// Generated by the private source repository's publish workflow.
globalThis.__A11Y_AUDIT_CONNECTOR__ = Object.freeze({
  "apiBaseUrl": "https://carlashub-accessibility-audit-connector.accessibility-audit-site-source.workers.dev",
  "githubAppSlug": ""
});
